# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths: [ ".devcontainer/**" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run tarball compression+
        # Copy file paths from `on.push.paths`
        run: |
          echo '[ ".devcontainer/**" ]' | tar -czvf ./artifact.tar.gz $(jq -r 'join(" ")')

      - name: Set properties
        id: properties
        run: |
          echo "date=$(date +"%Y%m%d.%H%M%S")" >> $GITHUB_OUTPUT
          echo "sha_short=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.properties.outputs.date }}
          name: Artifact@${{ steps.properties.outputs.sha_short }}
          artifacts: ./artifact.tar.gz
          artifactContentType: application/x-gzip
